# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('carousel', wagtail.wagtailcore.blocks.StructBlock((('carousel_title', wagtail.wagtailcore.blocks.CharBlock()), ('button', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('arrow', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)))), icon='image'))))), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java')], default='python', null=False)), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
    ]
